routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\PertanyaanController;

Route::get('/', 'HomeController@index');
Route::get('/data-table', 'HomeController@data');
Route::resource('pertanyaan', 'PertanyaanController');

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
   protected $table = 'pertanyaan';
   protected $fillable = ['judul','isi'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('home');
    }

    public function data(){
        return view('data');
    }

}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use App\Pertanyaan;
use Illuminate\Http\Request;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pertanyaan = Pertanyaan::all();
        return view('pertanyaan.pertanyaan')->with(['pertanyaan' => $pertanyaan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pertanyaan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pertanyaan = $request->all();
        //dd($pertanyaan);
        Pertanyaan::create($pertanyaan);
        return redirect('pertanyaan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item =pertanyaan::find($id);
        return view('pertanyaan/show')->with(['pertanyaan' => $item]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pertanyaan = Pertanyaan::find($id);
        return view('pertanyaan.edit_pertanyaan')->with(['pertanyaan' => $pertanyaan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $pertanyaan)
    {
        $edit = $request->all();
        Pertanyaan::find($pertanyaan)->update($edit);
        return redirect('pertanyaan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $item =pertanyaan::find($id);
       $item->delete();
       return redirect('pertanyaan');
    }
}

resources/views/data.blade.php
@extends('layouts.master')
@section('content')
    

<div class="card">
    <div class="card-header">
      <h3 class="card-title">DataTable with default features</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>Rendering engine</th>
          <th>Browser</th>
          <th>Platform(s)</th>
          <th>Engine version</th>
          <th>CSS grade</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Trident</td>
          <td>Internet
            Explorer 4.0
          </td>
          <td>Win 95+</td>
          <td> 4</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Trident</td>
          <td>Internet
            Explorer 5.0
          </td>
          <td>Win 95+</td>
          <td>5</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Trident</td>
          <td>Internet
            Explorer 5.5
          </td>
          <td>Win 95+</td>
          <td>5.5</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Trident</td>
          <td>Internet
            Explorer 6
          </td>
          <td>Win 98+</td>
          <td>6</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Trident</td>
          <td>Internet Explorer 7</td>
          <td>Win XP SP2+</td>
          <td>7</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Trident</td>
          <td>AOL browser (AOL desktop)</td>
          <td>Win XP</td>
          <td>6</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Firefox 1.0</td>
          <td>Win 98+ / OSX.2+</td>
          <td>1.7</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Firefox 1.5</td>
          <td>Win 98+ / OSX.2+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Firefox 2.0</td>
          <td>Win 98+ / OSX.2+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Firefox 3.0</td>
          <td>Win 2k+ / OSX.3+</td>
          <td>1.9</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Camino 1.0</td>
          <td>OSX.2+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Camino 1.5</td>
          <td>OSX.3+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Netscape 7.2</td>
          <td>Win 95+ / Mac OS 8.6-9.2</td>
          <td>1.7</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Netscape Browser 8</td>
          <td>Win 98SE+</td>
          <td>1.7</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Netscape Navigator 9</td>
          <td>Win 98+ / OSX.2+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.0</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.1</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.1</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.2</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.2</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.3</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.3</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.4</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.4</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.5</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.5</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.6</td>
          <td>Win 95+ / OSX.1+</td>
          <td>1.6</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.7</td>
          <td>Win 98+ / OSX.1+</td>
          <td>1.7</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Mozilla 1.8</td>
          <td>Win 98+ / OSX.1+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Seamonkey 1.1</td>
          <td>Win 98+ / OSX.2+</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Gecko</td>
          <td>Epiphany 2.20</td>
          <td>Gnome</td>
          <td>1.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>Safari 1.2</td>
          <td>OSX.3</td>
          <td>125.5</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>Safari 1.3</td>
          <td>OSX.3</td>
          <td>312.8</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>Safari 2.0</td>
          <td>OSX.4+</td>
          <td>419.3</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>Safari 3.0</td>
          <td>OSX.4+</td>
          <td>522.1</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>OmniWeb 5.5</td>
          <td>OSX.4+</td>
          <td>420</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>iPod Touch / iPhone</td>
          <td>iPod</td>
          <td>420.1</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Webkit</td>
          <td>S60</td>
          <td>S60</td>
          <td>413</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 7.0</td>
          <td>Win 95+ / OSX.1+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 7.5</td>
          <td>Win 95+ / OSX.2+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 8.0</td>
          <td>Win 95+ / OSX.2+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 8.5</td>
          <td>Win 95+ / OSX.2+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 9.0</td>
          <td>Win 95+ / OSX.3+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 9.2</td>
          <td>Win 88+ / OSX.3+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera 9.5</td>
          <td>Win 88+ / OSX.3+</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Opera for Wii</td>
          <td>Wii</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Nokia N800</td>
          <td>N800</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Presto</td>
          <td>Nintendo DS browser</td>
          <td>Nintendo DS</td>
          <td>8.5</td>
          <td>C/A<sup>1</sup></td>
        </tr>
        <tr>
          <td>KHTML</td>
          <td>Konqureror 3.1</td>
          <td>KDE 3.1</td>
          <td>3.1</td>
          <td>C</td>
        </tr>
        <tr>
          <td>KHTML</td>
          <td>Konqureror 3.3</td>
          <td>KDE 3.3</td>
          <td>3.3</td>
          <td>A</td>
        </tr>
        <tr>
          <td>KHTML</td>
          <td>Konqureror 3.5</td>
          <td>KDE 3.5</td>
          <td>3.5</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Tasman</td>
          <td>Internet Explorer 4.5</td>
          <td>Mac OS 8-9</td>
          <td>-</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Tasman</td>
          <td>Internet Explorer 5.1</td>
          <td>Mac OS 7.6-9</td>
          <td>1</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Tasman</td>
          <td>Internet Explorer 5.2</td>
          <td>Mac OS 8-X</td>
          <td>1</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>NetFront 3.1</td>
          <td>Embedded devices</td>
          <td>-</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>NetFront 3.4</td>
          <td>Embedded devices</td>
          <td>-</td>
          <td>A</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>Dillo 0.8</td>
          <td>Embedded devices</td>
          <td>-</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>Links</td>
          <td>Text only</td>
          <td>-</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>Lynx</td>
          <td>Text only</td>
          <td>-</td>
          <td>X</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>IE Mobile</td>
          <td>Windows Mobile 6</td>
          <td>-</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Misc</td>
          <td>PSP browser</td>
          <td>PSP</td>
          <td>-</td>
          <td>C</td>
        </tr>
        <tr>
          <td>Other browsers</td>
          <td>All others</td>
          <td>-</td>
          <td>-</td>
          <td>U</td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
          <th>Rendering engine</th>
          <th>Browser</th>
          <th>Platform(s)</th>
          <th>Engine version</th>
          <th>CSS grade</th>
        </tr>
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

  @endsection
  @push('script')
  <script src="../../plugins/datatables/jquery.dataTables.min.js"></script>
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="../../plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="../../plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
    });
  </script>
  @endpush

resources/views/home.blade.php
@extends('layouts.master')
@section('content')

<div class="container-fluid">
<div class="card">
    <div class="card-body">

        <table class="table table-bordered">
            <thead>                  
              <tr>
                <th style="width: 10px">#</th>
                <th>Task</th>
                <th>Progress</th>
                <th style="width: 40px">Label</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1.</td>
                <td>Update software</td>
                <td>
                  <div class="progress progress-xs">
                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                  </div>
                </td>
                <td><span class="badge bg-danger">55%</span></td>
              </tr>
              <tr>
                <td>2.</td>
                <td>Clean database</td>
                <td>
                  <div class="progress progress-xs">
                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                  </div>
                </td>
                <td><span class="badge bg-warning">70%</span></td>
              </tr>
              <tr>
                <td>3.</td>
                <td>Cron job running</td>
                <td>
                  <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                  </div>
                </td>
                <td><span class="badge bg-primary">30%</span></td>
              </tr>
              <tr>
                <td>4.</td>
                <td>Fix and squish bugs</td>
                <td>
                  <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar bg-success" style="width: 90%"></div>
                  </div>
                </td>
                <td><span class="badge bg-success">90%</span></td>
              </tr>
            </tbody>
          </table>

    </div>
</div>
</div>

@endsection

resources/views/pertanyaan/create.blade.php
@extends('layouts.master')
@section('content')
     <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Tambah Pertanyaan</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form action="/pertanyaan" method="POST">
                            @csrf
                            <div class="form-group">
                              <label for="exampleInputEmail1">Judul Pertanyaan</label>
                              <input type="text" class="form-control" id="exampleInputEmail1" name="judul">
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Isi</label>
                              <textarea class="form-control" id="exampleInputPassword1" name="isi"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Tambah</button>
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/pertanyaan/edit_pertanyaan.blade.php
@extends('layouts.master')
@section('content')
     <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Tambah Pertanyaan</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form action="/pertanyaan/{{$pertanyaan->id}}" method="POST">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                              <label for="exampleInputEmail1">Judul Pertanyaan</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="judul" value="{{$pertanyaan->judul}}">
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Isi</label>
                              <textarea class="form-control" id="exampleInputPassword1" name="isi">{{$pertanyaan->isi}} </textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Edit</button>
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/pertanyaan/pertanyaan.blade.php
@extends('layouts.master')
@section('content')
     <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Pertanyaan</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
          @forelse ($pertanyaan as $p)
          <div class="col-md-4">
            <div class="card card-widget">
              <div class="card-header">
                <div class="user-block">
                  <img class="img-circle" src="../dist/img/user1-128x128.jpg" alt="User Image">
                <span class="username"><a href="pertanyaan/{{$p->id}}">Orang</a></span>
                  <span class="description">{{$p->created_at}}</span>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                  <a class="btn btn-tool" href="pertanyaan/{{$p->id}}/edit">Edit</a>
                  <form action="{{route('pertanyaan.destroy',[$p->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-tool text-danger">Delete</button>               
                  </form>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                {{-- <img class="img-fluid pad" src="../dist/img/photo2.png" alt="Photo"> --}}
                <h3><strong>{{$p->judul}}</strong></h3>
                <p>{{$p->isi}}</p>
                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-thumbs-down"></i> Dislike</button>
              </div>
              <!-- /.card-body -->
              {{-- <div class="card-footer card-comments">
                <div class="card-comment">
                  <!-- User image -->
                  <img class="img-circle img-sm" src="../dist/img/user3-128x128.jpg" alt="User Image">

                  <div class="comment-text">
                    <span class="username">
                      Maria Gonzales
                      <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->
                <div class="card-comment">
                  <!-- User image -->
                  <img class="img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="User Image">

                  <div class="comment-text">
                    <span class="username">
                      Luna Stark
                      <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->
              </div> --}}
              <!-- /.card-footer -->
              <div class="card-footer">
                <form action="#" method="post">
                  <img class="img-fluid img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="Alt Text">
                  <!-- .img-push is used to add margin to elements next to floating images -->
                  <div class="img-push">
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                  </div>
                </form>
              </div>
              <!-- /.card-footer -->
            </div>
            {{-- <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{$p->judul}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{$p->created_at}}</h6>
                <p class="card-text">{{$p->isi}}</p>
                <a href="#" class="card-link">Edit</a>
                <a href="#" class="card-link text-danger">Hapus</a>
              </div>
            </div> --}}
          </div>
          @empty
              <h1>Belum Ada Pertanyaan</h1>
          @endforelse
        </div>
    </div>
</section>
@endsection

resources/views/pertanyaan/show.blade.php
@extends('layouts.master')
@section('content')
     <!-- Content Header (Page header) -->
 <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          
          
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
          
          <div class="col-md-12">
            <div class="card card-widget">
              <div class="card-header">
                <div class="user-block">
                  <img class="img-circle" src="../dist/img/user1-128x128.jpg" alt="User Image">
                <span class="username"><a href="pertanyaan/{{$pertanyaan->id}}">Orang</a></span>
                  <span class="description">{{$pertanyaan->created_at}}</span>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                  <a class="btn btn-tool" href="pertanyaan/{{$pertanyaan->id}}/edit">Edit</a>
                  <form action="{{route('pertanyaan.destroy',[$pertanyaan->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-tool text-danger">Delete</button>               
                  </form>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                {{-- <img class="img-fluid pad" src="../dist/img/photo2.png" alt="Photo"> --}}
                <h3><strong>{{$pertanyaan->judul}}</strong></h3>
                <p>{{$pertanyaan->isi}}</p>
                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-thumbs-down"></i> Dislike</button>
              </div>
             
              <div class="card-footer">
                <form action="#" method="post">
                  <img class="img-fluid img-circle img-sm" src="../dist/img/user4-128x128.jpg" alt="Alt Text">
                  <!-- .img-push is used to add margin to elements next to floating images -->
                  <div class="img-push">
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                  </div>
                </form>
              </div>
              <!-- /.card-footer -->
            </div>
           
          </div>
          
        </div>
    </div>
</section>
@endsection